### ISSUE TITLE
Error setup.py

### ISSUE THREAD

**Issue by congaterori** [Almas-Ali/Num6#1]
C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'keyword'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by Almas-Ali** [comment]
Use ' pip install num6 ' to install or if you want to install from source then in project folder open terminal and type ' python setup.py install '.
